let suggestions = [
    "Pimpri-Chinchwad Houses",
    "Mumbai Housing India",
    "Shimla, India",
    "Patna, India",
    "Gaziabad, India",
    "Delhi, India",
    "Mumbai, India",
    "Trivandrum, India",
    "Chennai, India",
    "Jaipur, India",
    "Kolkata, India",
    "Thane, India",
    "Dadar, India",
    "Indore, India",
    "Raipur, India",
    "Mesra, Inida",
    "Vishakapatnam",
    "Coaimbtore",
    "Gorakhpur",
    "Jhunjhunu",
    "Surat, India",
    "Durgapur",
    "Ambala",
    "Nanital",
    "srinagar",
    "Vellore",
    "Guwathi",
];